sudo: required

language: cpp

services:
  - docker

before_install:
  - echo "$TRAVIS_TAG"
  - echo "$TRAVIS_BRANCH"

env:
  - DOCKERFILE=Dockerfile DOCKERNAME=""
  - DOCKERFILE=share/golosd/docker/Dockerfile-test DOCKERNAME="-test"
  - DOCKERFILE=share/golosd/docker/Dockerfile-testnet DOCKERNAME="-testnet"
  - DOCKERFILE=share/golosd/docker/Dockerfile-lowmem DOCKERNAME="-lowmem"
  - DOCKERFILE=share/golosd/docker/Dockerfile-mongo DOCKERNAME="-mongo"

matrix:
  fast_finish: true

script:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      export DOCKERNAME="latest""$DOCKERNAME";
      export EXPORTNAME="$DOCKERNAME";
    elif [ -n "$TRAVIS_TAG" ]; then
      export DOCKERNAME="$TRAVIS_TAG""$DOCKERNAME";
      export EXPORTNAME="$DOCKERNAME";
    elif [ "$DOCKERNAME" == "-testnet" ] || [ "$DOCKERNAME" == "-test" ]; then
      export DOCKERNAME=develop"$DOCKERNAME";
    else
      export DOCKERNAME="";
    fi
  - echo "$DOCKERFILE"
  - echo "$DOCKERNAME"
  - if [ -n "$DOCKERNAME" ]; then
      docker build -t goloschain/golos:"$DOCKERNAME" -f "$DOCKERFILE" .;
    fi

after_success:
  - echo "$EXPORTNAME"
  - docker images
  - if [ -n "$EXPORTNAME" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push goloschain/golos:"$EXPORTNAME";
    fi
  - if [ "$TRAVIS_BRANCH" == "master" -a "$EXPORTNAME" == "latest" ]; then
      bash deploy/deploy.sh;
    fi
