name: livetest

on:
  push:
    branches: golos-v0.25.1

jobs:
  livetest:
    runs-on: ubuntu-16.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: ./share/golosd/docker/Dockerfile-livetest
          push: true
          tags: golosblockchain/golos:livetest
